apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: luksa/kubia-unhealthy       ❶
    name: kubia
    livenessProbe:                     ❷
      httpGet:                         ❷
        path: /                        ❸
        port: 8080                     ❹


❶ This is the image containing the (somewhat) broken app.
❷ A liveness probe that will perform an HTTP GET
❸ The path to request in the HTTP request
❹ The network port the probe should connect to

